return function (self) 
self.TextTable[0] = _EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Face/Text")
self.TextTable[1] = _EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Hair/Text")
self.TextTable[2] = _EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Top/Text")
self.TextTable[3] = _EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Pants/Text")
self.TextTable[4] = _EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Shoes/Text")
self.TextTable[5] = _EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Weapon/Text")
self.TextTable[6] = _EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Gender/Text")

_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Face/BtLeft"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeFace(-1)		
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Face/BtRight"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeFace(1)
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Hair/BtLeft"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeHair(-1)		
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Hair/BtRight"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeHair(1)
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Top/BtLeft"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeTop(-1)		
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Top/BtRight"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeTop(1)
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Pants/BtLeft"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangePants(-1)		
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Pants/BtRight"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangePants(1)
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Shoes/BtLeft"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeShoes(-1)		
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Shoes/BtRight"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeShoes(1)
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Weapon/BtLeft"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeWeapon(-1)		
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Weapon/BtRight"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeWeapon(1)
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Gender/BtLeft"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeGender(-1)		
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/Customization/Gender/BtRight"):ConnectEvent(ButtonClickEvent, function()
	self:OnChangeGender(1)
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/BtCancel"):ConnectEvent(ButtonClickEvent, function()
	if (self.Disabled) then
		return
	end
	self.LoginEngine:MoveToStep(1)
end)
_EntityService:GetEntityByPath("/ui/LoginUIGroup/CharacterCreationUI/Creation/Board/BtOk"):ConnectEvent(ButtonClickEvent, function()
	if (self.Disabled) then
		return
	end
	self:OnCreateCharacter()
end)
self.NameText.Entity:ConnectEvent(TextInputValueChangeEvent, function(event)
	self:OnNameTextChanged(event)
end)
end