return function (self) 
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "----------------- 도움말 -----------------")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "/파티만들기 : 새로운 파티를 만든다.")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "/파티탈퇴 : 현재 파티에 가입되어있는 경우 빠져나간다.")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "/파티초대 캐릭터이름 : 파티에 초대한다.(파티장만)")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "/파티강퇴 캐릭터이름 : 강제로 파티 퇴장시킨다.(파티장만)")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "/게임교환 캐릭터이름 : 게임아이템 교환신청을 한다.")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "/채널 : 같은 월드 인스턴스의 모두를 대화 상대로 설정한다.")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "/파티 : 접속해 있는 파티원을 대화 상대로 설정한다.")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "/귓말 캐릭터이름 : 귓속말 상태로 설정 (캐릭터이름 생략시 최근상대)")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "/모두 : 귓속말이 아닌 일반대화로 설정")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "* 채팅 입력창을 열고 Tab 키를 누르거나 채팅 입력창을 닫고")
_ChatMessageLogic:Add(_ChatMessageType.Yellow, "숫자키 1, 2, 3을 누르면 대화 상대를 다르게 설정할 수 있습니다.")
end