return function (self) 
self:LinkTo(self.Cap, -_BodyParts.Cap)
self:LinkTo(self.FaceAcc, -_BodyParts.FaceAcc)
self:LinkTo(self.EyeAcc, -_BodyParts.EyeAcc)
self:LinkTo(self.EarAcc, -_BodyParts.EarAcc)
self:LinkTo(self.Ring1, -_BodyParts.Ring1)
self:LinkTo(self.Ring2, -_BodyParts.Ring2)
self:LinkTo(self.Weapon, -_BodyParts.Weapon)
self:LinkTo(self.Shield, -_BodyParts.Shield)
self:LinkTo(self.Ring3, -_BodyParts.Ring3)
self:LinkTo(self.Ring4, -_BodyParts.Ring4)
--self:LinkTo(self.PetAcc, _BodyParts.pet)
--self:LinkTo(self.PetHp, _BodyParts.pet)
self:LinkTo(self.Cape, -_BodyParts.Cape)
self:LinkTo(self.Clothes, -_BodyParts.Clothes)
self:LinkTo(self.Gloves, -_BodyParts.Gloves)
self:LinkTo(self.Pants, -_BodyParts.Pants)
self:LinkTo(self.Shoes, -_BodyParts.Shoes)
self:LinkConsume(self.PetHp, _ConsumeItemElementType.HP)
self:LinkConsume(self.PetMp, _ConsumeItemElementType.MP)
self:UpdateEquipment()
end