return function (self,func) 
if (func == _FuncKeySystemType.Equip) then return true
elseif (func == _FuncKeySystemType.Inven) then return true
elseif (func == _FuncKeySystemType.Stat) then return true
elseif (func == _FuncKeySystemType.Skill) then return true
elseif (func == _FuncKeySystemType.Friend) then return true
elseif (func == _FuncKeySystemType.WorldMap) then return true
elseif (func == _FuncKeySystemType.Messenger) then return true
elseif (func == _FuncKeySystemType.MiniMap) then return true
elseif (func == _FuncKeySystemType.Quest) then return true
elseif (func == _FuncKeySystemType.KeySetting) then return true
elseif (func == _FuncKeySystemType.ToAll) then return true
elseif (func == _FuncKeySystemType.Whisper) then return true
elseif (func == _FuncKeySystemType.ToParty) then return true
elseif (func == _FuncKeySystemType.ToFriend) then return true
elseif (func == _FuncKeySystemType.Shortcut) then return true
elseif (func == _FuncKeySystemType.Quickslot) then return true
elseif (func == _FuncKeySystemType.ChattingPlus) then return true
elseif (func == _FuncKeySystemType.Guild) then return true
elseif (func == _FuncKeySystemType.ToGuild) then return true
elseif (func == _FuncKeySystemType.Party) then return true
elseif (func == _FuncKeySystemType.Notifier) then return true
elseif (func == _FuncKeySystemType.PickUp) then return true
elseif (func == _FuncKeySystemType.Sit) then return true
elseif (func == _FuncKeySystemType.Attack) then return true
elseif (func == _FuncKeySystemType.Jump) then return true
elseif (func == _FuncKeySystemType.EmotionHit) then return true
elseif (func == _FuncKeySystemType.EmotionSmile) then return true
elseif (func == _FuncKeySystemType.EmotionTroubled) then return true
elseif (func == _FuncKeySystemType.EmotionCry) then return true
elseif (func == _FuncKeySystemType.EmotionAngry) then return true
elseif (func == _FuncKeySystemType.EmotionBewildered) then return true
elseif (func == _FuncKeySystemType.EmotionStunned) then return true
elseif (func == _FuncKeySystemType.Down) then return true
elseif (func == _FuncKeySystemType.Esc) then return true
elseif (func == _FuncKeySystemType.Up) then return true
elseif (func == _FuncKeySystemType.Left) then return true
elseif (func == _FuncKeySystemType.Right) then return true
else return false end
end