return function (self,key) 
local k = KeyboardKey.CastFrom(key)
if (k == KeyboardKey.Alpha1) then return 2
elseif (k == KeyboardKey.Alpha2) then return 3
elseif (k == KeyboardKey.Alpha3) then return 4
elseif (k == KeyboardKey.Alpha4) then return 5
elseif (k == KeyboardKey.Alpha5) then return 6
elseif (k == KeyboardKey.Alpha6) then return 7
elseif (k == KeyboardKey.Alpha7) then return 8
elseif (k == KeyboardKey.Alpha8) then return 9
elseif (k == KeyboardKey.Alpha9) then return 10
elseif (k == KeyboardKey.Alpha0) then return 11
elseif (k == KeyboardKey.Minus) then return 12
elseif (k == KeyboardKey.Equals) then return 13
elseif (k == KeyboardKey.Q) then return 16
elseif (k == KeyboardKey.W) then return 17
elseif (k == KeyboardKey.E) then return 18
elseif (k == KeyboardKey.R) then return 19
elseif (k == KeyboardKey.T) then return 20
elseif (k == KeyboardKey.Y) then return 21
elseif (k == KeyboardKey.U) then return 22
elseif (k == KeyboardKey.I) then return 23
elseif (k == KeyboardKey.O) then return 24
elseif (k == KeyboardKey.P) then return 25
elseif (k == KeyboardKey.LeftBracket) then return 26
elseif (k == KeyboardKey.RightBracket) then return 27
elseif (k == KeyboardKey.LeftControl) then return 29
elseif (k == KeyboardKey.A) then return 30
elseif (k == KeyboardKey.S) then return 31
elseif (k == KeyboardKey.D) then return 32
elseif (k == KeyboardKey.F) then return 33
elseif (k == KeyboardKey.G) then return 34
elseif (k == KeyboardKey.H) then return 35
elseif (k == KeyboardKey.J) then return 36
elseif (k == KeyboardKey.K) then return 37
elseif (k == KeyboardKey.L) then return 38
elseif (k == KeyboardKey.Semicolon) then return 39
elseif (k == KeyboardKey.Quote) then return 40
elseif (k == KeyboardKey.Tilde) then return 41
elseif (k == KeyboardKey.LeftShift) then return 42
elseif (k == KeyboardKey.Backslash) then return 43
elseif (k == KeyboardKey.Z) then return 44
elseif (k == KeyboardKey.X) then return 45
elseif (k == KeyboardKey.C) then return 46
elseif (k == KeyboardKey.V) then return 47
elseif (k == KeyboardKey.B) then return 48
elseif (k == KeyboardKey.N) then return 49
elseif (k == KeyboardKey.M) then return 50
elseif (k == KeyboardKey.Comma) then return 51
elseif (k == KeyboardKey.Period) then return 52
elseif (k == KeyboardKey.LeftAlt) then return 56
elseif (k == KeyboardKey.Space) then return 57
elseif (k == KeyboardKey.F1) then return 59
elseif (k == KeyboardKey.F2) then return 60
elseif (k == KeyboardKey.F3) then return 61
elseif (k == KeyboardKey.F4) then return 62
elseif (k == KeyboardKey.F5) then return 63
elseif (k == KeyboardKey.F6) then return 64
elseif (k == KeyboardKey.F7) then return 65
elseif (k == KeyboardKey.F8) then return 66
elseif (k == KeyboardKey.F9) then return 67
elseif (k == KeyboardKey.F10) then return 68
elseif (k == KeyboardKey.F11) then return 87
elseif (k == KeyboardKey.F12) then return 88
elseif (k == KeyboardKey.Home) then return 71
elseif (k == KeyboardKey.PageUp) then return 73
elseif (k == KeyboardKey.End) then return 79
elseif (k == KeyboardKey.PageDown) then return 81
elseif (k == KeyboardKey.Insert) then return 82
elseif (k == KeyboardKey.Delete) then return 83
end
end